const mockHospitals = [
    {
        id: 'h1',
        name: 'City General Hospital',
        location: 'Downtown, Mumbai',
        rating: 4.5,
        discount_percentage: 15,
        discount_description: 'Flat 15% off on all lab tests',
        image_url: 'https://images.unsplash.com/photo-1586773860418-d373a2157dcc?q=80&w=1000&auto=format&fit=crop',
        phone_number: '9876543210',
        map_url: 'https://maps.google.com'
    },
    {
        id: 'h2',
        name: 'St. Mary\'s Specialty Clinic',
        location: 'Andheri West, Mumbai',
        rating: 4.8,
        discount_percentage: 20,
        discount_description: 'Special weekend health package',
        image_url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1000&auto=format&fit=crop',
        phone_number: '9999999999',
        map_url: 'https://maps.google.com'
    },
    {
        id: 'h3',
        name: 'Sunshine Pediatric Care',
        location: 'Bandra, Mumbai',
        rating: 4.2,
        discount_percentage: 10,
        discount_description: 'Free consultation for kids below 5',
        image_url: 'https://images.unsplash.com/photo-1505751172107-1bc596d13dcc?q=80&w=1000&auto=format&fit=crop',
        phone_number: '8888888888',
        map_url: 'https://maps.google.com'
    },
    {
        id: 'h_lupin',
        name: 'Lupin Diagnostic Lab',
        location: 'Indore, Madhya Pradesh',
        rating: 4.6,
        discount_percentage: 10,
        discount_description: 'Flat 10% off on all diagnostic tests',
        image_url: 'https://images.unsplash.com/photo-1579154204601-01588f351167?auto=format&fit=crop&q=80&w=1000',
        phone_number: '9111122222',
        map_url: 'https://maps.google.com/?q=Lupin+Diagnostic+Lab+Indore'
    }
];

const mockServices = [
    {
        id: 's1',
        hospital_id: 'h1',
        name: 'Full Body Health Checkup',
        category: 'Lab',
        price: 2500,
        discount_price: 1999,
        description: 'Comprehensive blood test and vital screening.',
        hospital_name: 'City General Hospital',
        hospital_location: 'Downtown, Mumbai'
    },
    {
        id: 's2',
        hospital_id: 'h1',
        name: 'Chest X-Ray',
        category: 'Scan',
        price: 800,
        discount_price: 650,
        description: 'High-resolution digital X-ray.',
        hospital_name: 'City General Hospital',
        hospital_location: 'Downtown, Mumbai'
    },
    {
        id: 's3',
        hospital_id: 'h2',
        name: 'Cardiology Consultation',
        category: 'OPD',
        price: 1000,
        discount_price: 800,
        description: 'Consultation with senior heart specialist.',
        hospital_name: 'St. Mary\'s Specialty Clinic',
        hospital_location: 'Andheri West, Mumbai'
    },
    {
        id: 's4',
        hospital_id: 'h3',
        name: 'Child Vaccination Package',
        category: 'Lab',
        price: 1500,
        discount_price: 1200,
        description: 'Monthly essential vaccines for toddlers.',
        hospital_name: 'Sunshine Pediatric Care',
        hospital_location: 'Bandra, Mumbai'
    },
    {
        id: 's_lupin_1',
        hospital_id: 'h_lupin',
        name: 'Complete Blood Count (CBC)',
        category: 'Lab',
        price: 320,
        discount_price: 288,
        description: 'Evaluates overall health and detects disorders such as anemia or leukemia.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_2',
        hospital_id: 'h_lupin',
        name: 'Peripheral Smear for Malaria Parasite (PS for MP)',
        category: 'Lab',
        price: 200,
        discount_price: 180,
        description: 'Microscopic examination of blood to detect malaria parasites.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_3',
        hospital_id: 'h_lupin',
        name: 'Widal Test',
        category: 'Lab',
        price: 250,
        discount_price: 225,
        description: 'Agglutination test to detect typhoid fever (enteric fever).',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_4',
        hospital_id: 'h_lupin',
        name: 'SGPT (ALT)',
        category: 'Lab',
        price: 150,
        discount_price: 135,
        description: 'Measures Alanine Aminotransferase level to assess liver function.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_5',
        hospital_id: 'h_lupin',
        name: 'SGOT (AST)',
        category: 'Lab',
        price: 150,
        discount_price: 135,
        description: 'Measures Aspartate Aminotransferase level to assess liver and heart health.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_6',
        hospital_id: 'h_lupin',
        name: 'Urine Routine & Microscopy (Urine RM)',
        category: 'Lab',
        price: 150,
        discount_price: 135,
        description: 'Evaluates urine sample for UTIs, kidney disease, or diabetes.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_7',
        hospital_id: 'h_lupin',
        name: 'C-Reactive Protein (CRP)',
        category: 'Lab',
        price: 500,
        discount_price: 450,
        description: 'Measures general inflammation levels in the body.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_8',
        hospital_id: 'h_lupin',
        name: 'Dengue NS1 Antigen',
        category: 'Lab',
        price: 600,
        discount_price: 540,
        description: 'Detects non-structural protein 1 of Dengue virus in early infection stages.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_9',
        hospital_id: 'h_lupin',
        name: 'Dengue Profile',
        category: 'Lab',
        price: 1750,
        discount_price: 1575,
        description: 'Comprehensive screening for Dengue infection including antigen and antibodies.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_10',
        hospital_id: 'h_lupin',
        name: 'Total Bilirubin',
        category: 'Lab',
        price: 250,
        discount_price: 225,
        description: 'Measures bilirubin level to diagnose jaundice or liver dysfunction.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_11',
        hospital_id: 'h_lupin',
        name: 'Creatinine',
        category: 'Lab',
        price: 150,
        discount_price: 135,
        description: 'Measures blood creatinine level to evaluate kidney function.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_12',
        hospital_id: 'h_lupin',
        name: 'Urea',
        category: 'Lab',
        price: 200,
        discount_price: 180,
        description: 'Measures blood urea nitrogen (BUN) level to assess kidney performance.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_13',
        hospital_id: 'h_lupin',
        name: 'Uric Acid',
        category: 'Lab',
        price: 200,
        discount_price: 180,
        description: 'Measures uric acid levels to detect gout or kidney stones.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_14',
        hospital_id: 'h_lupin',
        name: 'Cholesterol Total',
        category: 'Lab',
        price: 200,
        discount_price: 180,
        description: 'Measures total blood cholesterol level to monitor cardiovascular risk.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_15',
        hospital_id: 'h_lupin',
        name: 'Triglycerides',
        category: 'Lab',
        price: 300,
        discount_price: 270,
        description: 'Measures triglyceride levels to evaluate cardiovascular health.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_16',
        hospital_id: 'h_lupin',
        name: 'Serum Electrolytes',
        category: 'Lab',
        price: 440,
        discount_price: 396,
        description: 'Measures sodium, potassium, and chloride levels in the blood.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_17',
        hospital_id: 'h_lupin',
        name: 'Prothrombin Time (PT/INR)',
        category: 'Lab',
        price: 400,
        discount_price: 360,
        description: 'Evaluates blood clotting time and monitors warfarin therapy.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_18',
        hospital_id: 'h_lupin',
        name: 'Calcium',
        category: 'Lab',
        price: 200,
        discount_price: 180,
        description: 'Measures blood calcium level to assess bone, nerve, and heart function.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_19',
        hospital_id: 'h_lupin',
        name: 'Hemoglobin (Hb%)',
        category: 'Lab',
        price: 150,
        discount_price: 135,
        description: 'Measures the amount of oxygen-carrying protein in red blood cells.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_20',
        hospital_id: 'h_lupin',
        name: 'Erythrocyte Sedimentation Rate (ESR)',
        category: 'Lab',
        price: 150,
        discount_price: 135,
        description: 'Measures red blood cell settling rate to detect inflammation.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_21',
        hospital_id: 'h_lupin',
        name: 'Rheumatoid Arthritis (RA) Factor',
        category: 'Lab',
        price: 650,
        discount_price: 585,
        description: 'Detects RA autoantibodies in blood to diagnose rheumatoid arthritis.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_22',
        hospital_id: 'h_lupin',
        name: 'HbA1c (Glycated Hemoglobin)',
        category: 'Lab',
        price: 700,
        discount_price: 630,
        description: 'Assesses long-term blood sugar levels over 2-3 months.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_23',
        hospital_id: 'h_lupin',
        name: 'Lipid Profile',
        category: 'Lab',
        price: 800,
        discount_price: 720,
        description: 'Comprehensive test for cholesterol, triglycerides, HDL, LDL, and VLDL.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_24',
        hospital_id: 'h_lupin',
        name: 'Liver Function Test (LFT)',
        category: 'Lab',
        price: 850,
        discount_price: 765,
        description: 'Evaluates liver enzymes, proteins, and bilirubin levels.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_25',
        hospital_id: 'h_lupin',
        name: 'Kidney Function Test (KFT)',
        category: 'Lab',
        price: 800,
        discount_price: 720,
        description: 'Evaluates kidney function through urea, creatinine, and electrolytes.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_26',
        hospital_id: 'h_lupin',
        name: 'Thyroid Profile (T3, T4, TSH)',
        category: 'Lab',
        price: 700,
        discount_price: 630,
        description: 'Measures thyroid hormones to assess thyroid activity.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_27',
        hospital_id: 'h_lupin',
        name: 'Thyroid Stimulating Hormone (TSH)',
        category: 'Lab',
        price: 300,
        discount_price: 270,
        description: 'Evaluates thyroid gland function.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_28',
        hospital_id: 'h_lupin',
        name: 'Free Thyroid Profile (FT3, FT4, TSH)',
        category: 'Lab',
        price: 800,
        discount_price: 720,
        description: 'Measures unbound, active forms of T3 and T4 hormones.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_29',
        hospital_id: 'h_lupin',
        name: 'Vitamin B12',
        category: 'Lab',
        price: 1150,
        discount_price: 1035,
        description: 'Measures Vitamin B12 level to check for deficiency and anemia.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_30',
        hospital_id: 'h_lupin',
        name: 'Vitamin D3',
        category: 'Lab',
        price: 1400,
        discount_price: 1260,
        description: 'Measures 25-hydroxyvitamin D to check bone and immune health.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_31',
        hospital_id: 'h_lupin',
        name: 'Iron Study / Profile',
        category: 'Lab',
        price: 600,
        discount_price: 540,
        description: 'Measures iron levels, ferritin, and total iron-binding capacity.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_32',
        hospital_id: 'h_lupin',
        name: 'Urine Culture & Sensitivity',
        category: 'Lab',
        price: 900,
        discount_price: 810,
        description: 'Identifies bacteria in urine and determines effective antibiotics.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_33',
        hospital_id: 'h_lupin',
        name: 'Immunoglobulin E (IgE) Total',
        category: 'Lab',
        price: 850,
        discount_price: 765,
        description: 'Measures total IgE levels to diagnose allergies or asthma.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_34',
        hospital_id: 'h_lupin',
        name: 'Fasting Blood Sugar (FBS)',
        category: 'Lab',
        price: 100,
        discount_price: 90,
        description: 'Measures blood glucose after an overnight fast.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_35',
        hospital_id: 'h_lupin',
        name: 'Post Prandial Blood Sugar (PPBS)',
        category: 'Lab',
        price: 100,
        discount_price: 90,
        description: 'Measures blood glucose 2 hours after a meal.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_36',
        hospital_id: 'h_lupin',
        name: 'Random Blood Sugar (RBS)',
        category: 'Lab',
        price: 100,
        discount_price: 90,
        description: 'Measures blood glucose at any time of day.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_37',
        hospital_id: 'h_lupin',
        name: 'Hemoglobin Electrophoresis',
        category: 'Lab',
        price: 1000,
        discount_price: 900,
        description: 'Detects abnormal forms of hemoglobin (e.g. thalassemia).',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_38',
        hospital_id: 'h_lupin',
        name: 'Antinuclear Antibody (ANA)',
        category: 'Lab',
        price: 1000,
        discount_price: 900,
        description: 'Detects autoantibodies to diagnose autoimmune diseases like lupus.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_39',
        hospital_id: 'h_lupin',
        name: 'Anti-Mullerian Hormone (AMH)',
        category: 'Lab',
        price: 1850,
        discount_price: 1665,
        description: 'Assesses ovarian reserve and fertility potential.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_40',
        hospital_id: 'h_lupin',
        name: 'Beta HCG (Serum)',
        category: 'Lab',
        price: 700,
        discount_price: 630,
        description: 'Measures HCG hormone to confirm pregnancy or screen developmental markers.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_41',
        hospital_id: 'h_lupin',
        name: 'Luteinizing Hormone (LH)',
        category: 'Lab',
        price: 600,
        discount_price: 540,
        description: 'Evaluates pituitary function and reproductive health.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_42',
        hospital_id: 'h_lupin',
        name: 'Follicle Stimulating Hormone (FSH)',
        category: 'Lab',
        price: 600,
        discount_price: 540,
        description: 'Evaluates ovarian or testicular function and fertility.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_43',
        hospital_id: 'h_lupin',
        name: 'Prolactin',
        category: 'Lab',
        price: 600,
        discount_price: 540,
        description: 'Measures prolactin levels to evaluate pituitary gland disorders.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_44',
        hospital_id: 'h_lupin',
        name: 'Dual Marker Test',
        category: 'Lab',
        price: 2250,
        discount_price: 2025,
        description: 'Prenatal screening test for genetic abnormalities in fetus.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_45',
        hospital_id: 'h_lupin',
        name: 'Prostate Specific Antigen (PSA)',
        category: 'Lab',
        price: 800,
        discount_price: 720,
        description: 'Screens for prostate gland inflammation or prostate cancer.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_46',
        hospital_id: 'h_lupin',
        name: 'TB Gold (QuantiFERON-TB)',
        category: 'Lab',
        price: 2600,
        discount_price: 2340,
        description: 'Interferon-gamma release assay to detect Tuberculosis infection.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_47',
        hospital_id: 'h_lupin',
        name: 'Anti-CCP Antibody',
        category: 'Lab',
        price: 1500,
        discount_price: 1350,
        description: 'Highly specific test to diagnose early rheumatoid arthritis.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_48',
        hospital_id: 'h_lupin',
        name: 'Cancer Antigen 125 (CA-125)',
        category: 'Lab',
        price: 1200,
        discount_price: 1080,
        description: 'Monitors ovarian cancer or evaluates pelvic masses.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_49',
        hospital_id: 'h_lupin',
        name: 'Testosterone Total',
        category: 'Lab',
        price: 800,
        discount_price: 720,
        description: 'Measures testosterone hormone levels in the blood.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_50',
        hospital_id: 'h_lupin',
        name: 'Stool Routine & Microscopy',
        category: 'Lab',
        price: 250,
        discount_price: 225,
        description: 'Screens stool sample for parasites, blood, or infections.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_51',
        hospital_id: 'h_lupin',
        name: 'Stool Culture & Sensitivity',
        category: 'Lab',
        price: 1000,
        discount_price: 900,
        description: 'Identifies bacterial pathogens in stool for gastrointestinal infections.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_52',
        hospital_id: 'h_lupin',
        name: 'Blood Culture & Sensitivity',
        category: 'Lab',
        price: 1500,
        discount_price: 1350,
        description: 'Detects systemic bacterial or fungal infections in blood.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_53',
        hospital_id: 'h_lupin',
        name: 'HIV 1 & 2 Antibody',
        category: 'Lab',
        price: 500,
        discount_price: 450,
        description: 'Screens for antibodies to Human Immunodeficiency Virus.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_54',
        hospital_id: 'h_lupin',
        name: 'Hepatitis C Virus (HCV)',
        category: 'Lab',
        price: 500,
        discount_price: 450,
        description: 'Detects antibodies to Hepatitis C Virus to identify infection.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_55',
        hospital_id: 'h_lupin',
        name: 'Hepatitis B Surface Antigen (HBsAg)',
        category: 'Lab',
        price: 400,
        discount_price: 360,
        description: 'Detects acute or chronic Hepatitis B infection.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_56',
        hospital_id: 'h_lupin',
        name: 'Syphilis (VDRL)',
        category: 'Lab',
        price: 300,
        discount_price: 270,
        description: 'Non-treponemal screening test for Syphilis infection.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    },
    {
        id: 's_lupin_57',
        hospital_id: 'h_lupin',
        name: 'Antenatal Care (ANC) Profile',
        category: 'Lab',
        price: 1500,
        discount_price: 1350,
        description: 'Routine blood and urine checkup package for pregnant women.',
        hospital_name: 'Lupin Diagnostic Lab',
        hospital_location: 'Indore, Madhya Pradesh'
    }
];

module.exports = { mockHospitals, mockServices };
